//
// Created by haydn on 20/01/2019.
//

#ifndef EXMACHINA_CONSTANTS_H
#define EXMACHINA_CONSTANTS_H

#endif //EXMACHINA_CONSTANTS_H
// game state enum
enum{SPLASH_SCREEN, MAIN_MENU, IN_GAME, TEXT_DISPLAY, PAUSE, INVENTORY, GAME_OVER};
// main menu options
enum{NEW_GAME, LOAD_GAME, EXIT_GAME};
// pause menu options
enum{CONTINUE_GAME, SAVE_GAME, QUIT_GAME};
// directions
enum{NORTH, EAST, SOUTH, WEST};
// foreground sprites
enum{COUNTER_LEFT, COUNTER_RIGHT, TABLE_TOP, TABLE_MIDDLE, TABLE_BOTTOM,
  FRIDGE_TOP, SINK_TOP, TABLE_LEFT, TABLE_CENTRE, TABLE_RIGHT, CHAIR_TOP,
  CHAIR_BOTTOM, COOKER_TOP, CAFE_TABLE_LEFT, CAFE_TABLE_RIGHT, SOFA_TOP_LEFT,
  SOFA_TOP_RIGHT, SOFA_LEFT_TOP, SOFA_LEFT_BOTTOM, SOFA_RIGHT_TOP,
  SOFA_RIGHT_BOTTOM, SOFA_BOTTOM_LEFT, SOFA_BOTTOM_RIGHT, BED_LEFT, BED_RIGHT,
  BED_TOP, BED_BOTTOM, FLOWER_TOP, FLOWER_MID_ONE, FLOWER_MID_TWO, FLOWER_BOTTOM,
  LAB_COAT, VENDING_MACHINE , WEIGHTBENCH_TOP, WEIGHTBENCH_BOTTOM, TREADMILL_TOP,
TREADMILL_BOTTOM, LOCKER_TOP, LOCKER_BOTTOM, SHOWER, TOILET_LEFT,
  BATHROOM_SINK_RIGHT, WASTE_BARREL, WASTE_BARREL_TWO, BOOKSHELF_LEFT,
BOOKSHELF_RIGHT, STORAGE_CRATE, SYNTH_TOP_LEFT, SYNTH_TOP_RIGHT,
  SYNTH_BOTTOM_LEFT, SYNTH_BOTTOM_RIGHT, SYNTH_TERMINAL, SURGEONS_TOOLS,
  POOL_TOP_LEFT, POOL_TOP_RIGHT, POOL_BOTTOM_LEFT, POOL_BOTTOM_RIGHT,
COMPUTERS_TOP_LEFT, COMPUTERS_TOP_CENTRE, COMPUTERS_TOP_RIGHT,
  COMPUTERS_LEFT_MIDDLE, COMPUTERS_LEFT_BOTTOM, COMPUTERS_RIGHT_MIDDLE,
COMPUTERS_RIGHT_BOTTOM, SYNTH_BRAIN, REACTOR_TOP_LEFT, REACTOR_TOP_RIGHT,
REACTOR_MIDDLE_LEFT, REACTOR_MIDDLE_RIGHT, REACTOR_BOTTOM_LEFT,
REACTOR_BOTTOM_RIGHT, DESK_RIGHT, DESK_LEFT, DESK_CHAIR_BOTTOM, SAFE,
SERVER_LEFT, SERVER_RIGHT};
// Wall sprites
enum{ TOP_LEFT, TOP, TOP_RIGHT, LEFT, RIGHT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT};
// rooms
enum{OFFICE_ONE, ATRIUM, CAFETERIA, LOUNGE, DORMS, GARDEN, GYM, LOCKERS,
  TOILETS_M, TOILETS_F, WASTE_DISPOSAL, LIBRARY, SUPPLY_ROOM, CORRIDOR, LAB_ONE, LAB_TWO,
OBSERVATION, TESTING, SERVERS, REACTOR, WORKSHOP, INFIRMARY, LEAD_TECH_OFFICE,
SECURITY, RECEPTION, EXIT};
// items
enum{ SCREWDRIVER, FUSE, KEYCARD_BLUE, CAN, LUNCHBOX, KEY, KEYCARD_RED,
  KEYCARD_GREEN, KEYCARD_YELLOW , HAMMER, PLIERS, MAGNIFIER};

const int NUM_FLOOR_SPRITES = 3;
const int NUM_WALL_SPRITES = 8;
const int NUM_FOREGROUND_SPRITES = 77;
const int NUM_ITEM_SPRITES = 12;
const int NUM_CLUE_SPRITES = 2;
const int NUM_SWITCH_SPRITES = 1;
const int NUM_EXIT_SPRITES = 4;
const int NUM_MOVABLE_SPRITES = 1;
const int NUM_PLAYER_SPRITES = 16;

const int NUM_ROOMS = 25;

const float GAME_HEIGHT = 768.0f;
const float GAME_WIDTH = 1366.0f;
const float GRID_SIZE = 75.0f;
const float DISTANCE_CHECK = 0.005f;
const float MOVABLE_DISTANCE_CHECK = 0.025f;
const float MOVEMENT_DISTANCE = 0.25f;